### ISSUE TITLE
Re-connect

### ISSUE THREAD

**Issue by tomberek** [dmotz/trystero#29]
I'm getting some re-connection difficulties.
1) Two clients connect (one is a phone).
2) Phone display is turned off.
3) 2 minutes later the connection is broken and the other browser shows this error in console.
```
crypto-254fb80e.js:232 Error: Connection failed.
    at Peer._onConnectionStateChange (simple-peer-light.js:550:28)
    at Peer._pc.onconnectionstatechange (simple-peer-light.js:105:12)
```

I attempted various combinations of `.leave()` and `.joinRoom` without luck.

**Comment by jeremyckahn** [comment]
This seems like it may be a [`simple-peer-light`](https://github.com/mitschabaude/simple-peer-light) issue. I've noticed that it doesn't handle reconnections after system suspension (sleep) well. Specifically, when there is an ICE connection failure, it doesn't attempt to reconnect: https://github.com/mitschabaude/simple-peer-light/blob/503028ee121687d87bb7042b24f6934a0b06ca14/index.js#L745-L752

I wonder if the connection failure can be detected by Trystero and so that it can attempt to reconnect? If not, `simple-peer-light` may need to be patched directly.

**Comment by tomberek** [comment]
The entire process cannot be restarted upon identification of the failure? I mean from the side of the suspended client.

**Comment by jeremyckahn** [comment]
> The entire process cannot be restarted upon identification of the failure? I mean from the side of the suspended client.

I'm not sure. It would probably take some experimentation. What I'm struggling with is how to trigger an ICE candidate failure so that error handling could be tested and debugged. Do have a reliable way of doing that?

**Comment by jeremyckahn** [comment]
I'm able to reliably reproduce the error state with two computers. On one computer, I just disable WiFi, wait 30-60 seconds, and turn it back on. The two peers can no longer connect. Leaving and rejoining the room on either computer doesn't reestablish connection.

_However_, I noticed that if **both** computers leave and rejoin the room, connection can successfully be reestablished. Sometimes it takes more than one try to leave and rejoin the room.

This suggests that the re-connection issue can be addressed within Trystero. It's worth exploring what the leave action is doing to clean up connections and see if it can be reused during a live connection as peers cycle in and out of the room.

**Comment by jeremyckahn** [comment]
I've got a PR to fix this at #30. @tomberek please test it out and see if it fixes the issue for you.

**Comment by tomberek** [comment]
Sadly, no. The same sequence of events still did not lead to a re-connection. I suspect one of the peers is trying, but no the other.

**Comment by tomberek** [comment]
@jeremyckahn Yes, #30 improves leave/rejoin behavior between desktop browsers. Thanks!

**Comment by jeremyckahn** [comment]
That's great to hear! Thanks for testing @tomberek.

If #30 seems good to @dmotz, I recommend merging and releasing the change when it's convenient but leaving this issue open. I predict that this problem will take time and iteration to truly solve, but it can be gradually improved over time with incremental fixes.

**Comment by dmotz** [comment]
I released the related PR as 0.11.8. I haven't had a chance to look into this much yet, but will try to explore soon. It may be worth doing some tests with the Firebase strategy to determine whether the problem lies on the matchmaking side or the WebRTC library side. If it's the latter I'm open to finding a new RTC connection management lib or building one in.

**Comment by jeremyckahn** [comment]
Thank you for the 0.11.8 release, @dmotz!

> It may be worth doing some tests with the Firebase strategy to determine whether the problem lies on the matchmaking side or the WebRTC library side.

That's a great idea. I've only used the WebTorrent strategy so far so I don't know how its reliability might compare to Firebase in practice. I've noticed that clients are generally able to connect to WebTorrent servers and exchange SDPs. I think the remaining issues (at least on desktop browsers) are specific longer-running sessions, which is going to be challenging to reproduce and debug.

I think the iOS issues are a result of limitations that Apple has built in paired with platform-specific bugs. For example:
  - https://bugs.webkit.org/show_bug.cgi?id=189503
  - https://stackoverflow.com/a/53914556

There may be only so much we can do for iOS until Apple fixes their platform-level issues. 😕

------------------------------------

In case it's helpful, https://www.farmhand.life/#online/global ([source](https://github.com/jeremyckahn/farmhand)) is running my Trystero branch (which, at the time of this comment, is in sync with the 0.11.8 release). I leave sessions running for days at a time, which is how I can observe the issues related to longer-lived sessions. It may be a helpful way to manifest issues for testing and debugging purposes.

**Comment by aehlke** [comment]
@jeremyckahn any updates on your experience?

**Comment by jeremyckahn** [comment]
> @jeremyckahn any updates on your experience?

No, it's about the same since my last comment. I haven't been exploring connection improvements since then.

**Comment by dmotz** [comment]
Closing this as there have been many updates to Trystero since this was reported. Re-open if needed.
